name: github_actions_gtest_example-Debug

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake g++ libgtest-dev
    - name: Build and install libhv
      run: |
        git clone --depth=1 https://github.com/ithewei/libhv.git
        cd libhv
        mkdir build && cd build
        cmake ..
        make -j$(nproc)
        sudo make install
    - name: Build and install protobuf
      run: |
        git clone --depth=1 --branch v21.12 https://github.com/protocolbuffers/protobuf.git
        cd protobuf
        git submodule update --init --recursive
        mkdir build && cd build
        cmake .. -DCMAKE_CXX_STANDARD=17
        make -j$(nproc)
        sudo make install
        sudo ldconfig
    - name: Build and install GoogleTest
      run: |
        cd /usr/src/googletest
        sudo cmake -DCMAKE_CXX_STANDARD=17 .
        sudo make
        sudo cp lib/*.a /usr/lib/
        sudo cp lib/*.a /usr/local/lib/
    - name: Verify gtest installation
      run: ls -l /usr/lib/libgtest*

    - uses: actions/checkout@v1

    - name: Configure CMake
      run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-Werror" ..

    - name: Build project
      run: cd build && make && ls -l

    - name: Run Tests
      run: find build -type f -executable -name "*Test" -exec {} \;
